# Generated by Django 3.1.6 on 2021-02-07 22:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Grocery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(blank=True, max_length=255, null=True)),
                ('item_quantity', models.CharField(blank=True, max_length=255, null=True)),
                ('item_status', models.CharField(blank=True, choices=[('pending', 'PENDING'), ('bought', 'BOUGHT'), ('left', 'LEFT'), ('not available', 'NOT AVAILABLE')], default='pending', max_length=255, null=True)),
                ('date', models.DateField(blank=True, max_length=255, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grocery', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
